#ifndef COMPAT_IPV6_H
#define COMPAT_IPV6_H

#include_next <net/ipv6.h>

/* Include the autogenerated header file */
#include "../../compat/config.h"

#ifndef HAVE_IPV6_ADDR_COPY
#define ipv6_addr_copy(a, b) (*(a) = *(b))
#endif

#endif /* COMPAT_IPV6_H */
